
name: Review
on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up dotnet 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: dotnet build
      - name: Set up test dependencies
        run: docker-compose -f Tests/docker-compose.yml up -d
      - name: Run tests
        run: dotnet test --logger "trx;LogFileName=results.trx"
      
        